apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app-deploy.yaml
  - app-service.yaml
  - app-ingress.yaml
  - registry.yaml
  - updater.yaml
  - db-deploy.yaml
  - db-service.yaml
  - secret.yaml
  - db-pvc.yaml
